In [1]:
import numpy as np

Create a numpy array starting from 2 till 50 with a stepsize of 3. 


In [2]:
arr=np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Accept two lists of 5 elements each from the user. 
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print 


In [3]:
lis1=[]
lst2=[]

def AddElement(ls):
    for i in range(5):
        num=int(input())
        ls.append(num)
    print(ls)
    
AddElement(lis1)
AddElement(lst2)



34
243
75
6
34
[34, 243, 75, 6, 34]
76
24
876
312
56
[76, 24, 876, 312, 56]


In [4]:
ls1=[]
for i in range(5):
    num=int(input())
    ls1.append(num)
print(ls1)

ls2=[]
for i in range(5):
    num=int(input())
    ls2.append(num)
print(ls2)

23
54
76
89
46
[23, 54, 76, 89, 46]
98
24
089
2
45
[98, 24, 89, 2, 45]


In [6]:

arr1=np.array(ls1)
arr2=np.array(ls2)

unsorted=np.concatenate((arr1,arr2))
unsorted

array([23, 54, 76, 89, 46, 98, 24, 89,  2, 45])

In [7]:
sortedArr=np.sort(unsorted)
sortedArr

array([ 2, 23, 24, 45, 46, 54, 76, 89, 89, 98])

Q3.  Write a code snippet to find the dimensions of a ndarray and its size. 

In [8]:
print(sortedArr.shape)

print(sortedArr.size)

(10,)
10


Q 4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims


In [9]:
sortedArr.shape

(10,)

In [12]:

print(sortedArr[:,np.newaxis].shape)
print("---------------------------------")
print(sortedArr[:,np.newaxis])


(10, 1)
---------------------------------
[[ 2]
 [23]
 [24]
 [45]
 [46]
 [54]
 [76]
 [89]
 [89]
 [98]]


In [13]:
print(sortedArr.shape)
new3D=np.expand_dims(sortedArr, axis=0)
new3D.shape

(10,)


(1, 10)

In [14]:
print(sortedArr.shape)
new3D=np.expand_dims(sortedArr, axis=1)
new3D.shape

(10,)


(10, 1)

In [15]:
print(sortedArr.shape)
new3D=np.expand_dims(sortedArr, axis=2)
new3D.shape

(10,)


AxisError: axis 2 is out of bounds for array of dimension 2

Q. 5 
Consider two square numpy arrays. Stack them vertically and horizontally. 
Hint: Use vstack(), hstack() 


In [18]:
a1=np.arange(1,32,2).reshape(4,4)
a1

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [19]:
a2=np.arange(1,48,3).reshape(4,4)
a2

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

In [25]:
horizontal=np.hstack((a1,a2))
horizontal

array([[ 1,  3,  5,  7,  1,  4,  7, 10],
       [ 9, 11, 13, 15, 13, 16, 19, 22],
       [17, 19, 21, 23, 25, 28, 31, 34],
       [25, 27, 29, 31, 37, 40, 43, 46]])

In [24]:
vertical=np.vstack((a1,a2))
vertical

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

Q 6.

How to get unique items and counts of unique items?

In [26]:
np.unique(horizontal)

array([ 1,  3,  4,  5,  7,  9, 10, 11, 13, 15, 16, 17, 19, 21, 22, 23, 25,
       27, 28, 29, 31, 34, 37, 40, 43, 46])

In [27]:
np.unique(horizontal).size

26